# Generated by Django 6.0.3 on 2026-04-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apiforwardrule',
            new_name='gateway_api_is_acti_dd006b_idx',
            old_name='gateway_apif_is_acti_3024c4_idx',
        ),
        migrations.RenameIndex(
            model_name='apiforwardrule',
            new_name='gateway_api_request_b86784_idx',
            old_name='gateway_apif_request_0180e6_idx',
        ),
    ]
