# Generated by Django 6.0.3 on 2026-04-11 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_rename_gateway_apif_is_acti_3024c4_idx_gateway_api_is_acti_dd006b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='后端名称')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='描述')),
                ('base_url', models.URLField(help_text='例如 https://openrouter.ai/api/v1', verbose_name='API 基础地址')),
                ('api_key', models.CharField(max_length=256, verbose_name='API Key')),
                ('weight', models.PositiveIntegerField(default=1, help_text='加权轮询时使用，值越大分配越多', verbose_name='权重')),
                ('max_rpm', models.PositiveIntegerField(default=0, help_text='0 表示不限制', verbose_name='每分钟最大请求数')),
                ('max_concurrent', models.PositiveIntegerField(default=0, help_text='0 表示不限制', verbose_name='最大并发数')),
                ('timeout_seconds', models.PositiveIntegerField(default=60, verbose_name='超时时间(秒)')),
                ('health_status', models.CharField(choices=[('healthy', '健康'), ('degraded', '降级'), ('down', '不可用')], default='healthy', max_length=20, verbose_name='健康状态')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='连续失败次数')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='最近健康检查')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='最近失败时间')),
                ('total_requests', models.BigIntegerField(default=0, verbose_name='总请求数')),
                ('total_tokens', models.BigIntegerField(default=0, verbose_name='总 Token 消耗')),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name='总费用(原始货币)')),
                ('rr_counter', models.BigIntegerField(default=0, verbose_name='轮询计数器')),
                ('extra_headers', models.JSONField(blank=True, default=dict, help_text='JSON 格式的额外 HTTP 头', verbose_name='附加请求头')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API 后端',
                'verbose_name_plural': 'API 后端',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200, verbose_name='模型ID')),
                ('is_stream', models.BooleanField(default=False, verbose_name='是否流式')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入 Tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出 Tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总 Tokens')),
                ('upstream_cost', models.DecimalField(decimal_places=8, default=0, max_digits=14, verbose_name='上游成本(原始)')),
                ('cost_cny', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='成本(人民币)')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='响应时间(ms)')),
                ('status_code', models.IntegerField(default=200, verbose_name='HTTP 状态码')),
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
            ],
            options={
                'verbose_name': 'API 请求日志',
                'verbose_name_plural': 'API 请求日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='规则名称')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='描述')),
                ('priority', models.IntegerField(default=100, help_text='值越小优先级越高', verbose_name='优先级')),
                ('match_type', models.CharField(choices=[('all', '全部匹配'), ('model_prefix', '模型前缀匹配'), ('model_exact', '模型精确匹配'), ('user_tier', '用户等级匹配')], default='all', max_length=20, verbose_name='匹配类型')),
                ('match_value', models.CharField(blank=True, help_text='模型前缀/精确模型ID/用户等级，all 类型留空', max_length=200, verbose_name='匹配值')),
                ('strategy', models.CharField(choices=[('round_robin', '轮询'), ('weighted', '加权轮询'), ('random', '随机'), ('least_used', '最少使用')], default='round_robin', max_length=20, verbose_name='负载策略')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '路由规则',
                'verbose_name_plural': '路由规则',
                'ordering': ['priority', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='apiforwardrule',
            name='gateway_api_is_acti_dd006b_idx',
        ),
        migrations.RemoveIndex(
            model_name='apiforwardrule',
            name='gateway_api_request_b86784_idx',
        ),
        migrations.DeleteModel(
            name='ApiForwardRule',
        ),
        migrations.AddIndex(
            model_name='apibackend',
            index=models.Index(fields=['is_active', 'health_status'], name='gateway_api_is_acti_91fecc_idx'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='backend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='gateway.apibackend', verbose_name='使用后端'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='routingrule',
            name='backends',
            field=models.ManyToManyField(help_text='匹配时可使用的后端列表', related_name='routing_rules', to='gateway.apibackend', verbose_name='目标后端'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='routing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.routingrule', verbose_name='匹配规则'),
        ),
        migrations.AddIndex(
            model_name='routingrule',
            index=models.Index(fields=['is_active', 'priority'], name='gateway_rou_is_acti_56cfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='routingrule',
            index=models.Index(fields=['match_type', 'match_value'], name='gateway_rou_match_t_952589_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user', '-created_at'], name='gateway_req_user_id_2f863c_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['backend', '-created_at'], name='gateway_req_backend_85e461_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['-created_at'], name='gateway_req_created_20a06a_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['model_id', '-created_at'], name='gateway_req_model_i_5e70b5_idx'),
        ),
    ]
