# Generated by Django 6.0.3 on 2026-04-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_apibackend_requestlog_routingrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='business_type',
            field=models.CharField(choices=[('chat', '聊天对话'), ('coding', '编程开发'), ('text2img', '文生图'), ('text2video', '文生视频'), ('translation', '翻译'), ('writing', '写作'), ('analysis', '数据分析'), ('general', '通用')], default='chat', max_length=20, verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='apibackend',
            name='extra_headers',
            field=models.JSONField(blank=True, default=dict, verbose_name='附加请求头'),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='backends',
            field=models.ManyToManyField(blank=True, related_name='routing_rules', to='gateway.apibackend', verbose_name='直接关联后端'),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='match_type',
            field=models.CharField(choices=[('all', '全部匹配'), ('model_prefix', '模型前缀匹配'), ('model_exact', '模型精确匹配'), ('user_tier', '用户等级匹配'), ('business_type', '业务类型匹配')], default='all', max_length=20, verbose_name='匹配类型'),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='match_value',
            field=models.CharField(blank=True, help_text='模型前缀/模型ID/用户等级/业务类型', max_length=200, verbose_name='匹配值'),
        ),
        migrations.CreateModel(
            name='BackendGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名称')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='描述')),
                ('strategy', models.CharField(choices=[('round_robin', '轮询'), ('weighted', '加权轮询'), ('random', '随机'), ('least_used', '最少使用')], default='round_robin', max_length=20, verbose_name='组内负载策略')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('backends', models.ManyToManyField(blank=True, related_name='groups', to='gateway.apibackend', verbose_name='成员后端')),
            ],
            options={
                'verbose_name': 'API 后端组',
                'verbose_name_plural': 'API 后端组',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='routingrule',
            name='backend_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='gateway.backendgroup', verbose_name='关联后端组'),
        ),
    ]
