# Generated by Django 6.0.3 on 2026-04-12 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_requestlog_business_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routingrule',
            name='match_users',
            field=models.ManyToManyField(blank=True, help_text='match_type 为 user_exact 时生效', related_name='routing_rules', to=settings.AUTH_USER_MODEL, verbose_name='指定用户'),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='match_type',
            field=models.CharField(choices=[('all', '全部匹配'), ('model_prefix', '模型前缀匹配'), ('model_exact', '模型精确匹配'), ('user_tier', '用户等级匹配'), ('user_exact', '指定用户匹配'), ('business_type', '业务类型匹配')], default='all', max_length=20, verbose_name='匹配类型'),
        ),
    ]
