# Generated by Django 6.0.3 on 2026-04-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_apibackend_multipliers_requestlog_stats_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibackend',
            name='pricing_multiplier',
            field=models.DecimalField(decimal_places=6, default=1, help_text='同步模型时：上游返回的单价 × 此系数写入 AIModel 定价字段', max_digits=12, verbose_name='模型定价倍率'),
        ),
        migrations.AlterField(
            model_name='apibackend',
            name='stats_request_multiplier',
            field=models.DecimalField(decimal_places=6, default=1, help_text='每条请求日志记录的统计权重，用于网关看板等效请求数（非整数可表示抽样/加权）', max_digits=12, verbose_name='请求统计系数'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='stats_weight',
            field=models.DecimalField(decimal_places=6, default=1, help_text='记录时刻的后端请求统计系数，聚合时累加此字段作为等效请求数', max_digits=12, verbose_name='统计权重'),
        ),
    ]
