# Generated by Django 6.0.3 on 2026-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_alter_apibackend_pricing_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apibackend',
            name='backend_type',
            field=models.CharField(choices=[('openai', 'OpenAI 兼容（OpenRouter / DeepSeek / 通义 / Moonshot 等）'), ('anthropic', 'Anthropic Messages（Claude / CMI Cloudcode / tokenrouterapi 等）')], default='openai', help_text='openai：标准 /v1/chat/completions；anthropic：/v1/messages（Claude 系，含 CMI Cloudcode）', max_length=20, verbose_name='后端协议类型'),
        ),
        migrations.AlterField(
            model_name='apibackend',
            name='base_url',
            field=models.URLField(help_text='OpenAI 系如 https://openrouter.ai/api/v1；Anthropic 系如 https://tokenrouterapi.com（无需 /v1 后缀，适配器会自行追加）', verbose_name='API 基础地址'),
        ),
    ]
