# Generated by Django 6.0.3 on 2026-03-15 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='充值金额(元)')),
                ('payment_method', models.CharField(choices=[('manual', '人工充值'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行转账'), ('other', '其他')], default='manual', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_orders', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值订单',
                'verbose_name_plural': '充值订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('recharge', '充值'), ('deduction', '消费'), ('refund', '退款'), ('adjustment', '人工调整'), ('reward', '奖励')], max_length=20, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='金额(+收/-支)')),
                ('balance_before', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='变动前余额')),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='变动后余额')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='描述')),
                ('related_message_id', models.IntegerField(blank=True, null=True, verbose_name='关联消息ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '账单流水',
                'verbose_name_plural': '账单流水',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='billing_bil_user_id_a4c87a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('model_id', models.CharField(blank=True, max_length=200, verbose_name='模型ID')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数')),
                ('token_count', models.BigIntegerField(default=0, verbose_name='Token总量')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='费用(元)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日用量',
                'verbose_name_plural': '每日用量',
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'model_id')},
            },
        ),
    ]
