# Generated by Django 6.0.3 on 2026-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('chat', '0004_alter_aimodel_options_aimodel_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='record_type',
            field=models.CharField(choices=[('recharge', '充值'), ('deduction', '消费'), ('refund', '退款'), ('adjustment', '人工调整'), ('reward', '奖励'), ('subscription', '套餐订阅')], max_length=20, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('tier', models.CharField(choices=[('free', '免费版'), ('basic', '基础版'), ('pro', '专业版'), ('enterprise', '企业版')], max_length=20, unique=True, verbose_name='套餐等级')),
                ('description', models.TextField(blank=True, verbose_name='套餐描述')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月租价格(元)')),
                ('monthly_token_limit', models.BigIntegerField(default=0, help_text='0 表示不限制', verbose_name='每月Token额度')),
                ('daily_request_limit', models.IntegerField(default=0, help_text='0 表示不限制', verbose_name='每日请求次数限制')),
                ('max_context_length', models.IntegerField(default=20, verbose_name='最大上下文条数')),
                ('allowed_business_types', models.JSONField(blank=True, default=list, help_text='JSON 数组，如 ["chat","coding"]，空数组表示全部', verbose_name='可用业务类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allowed_models', models.ManyToManyField(blank=True, help_text='留空表示可用全部已启用模型', related_name='allowed_plans', to='chat.aimodel', verbose_name='可用模型')),
            ],
            options={
                'verbose_name': '套餐方案',
                'verbose_name_plural': '套餐方案',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
    ]
