# Generated by Django 6.0.3 on 2026-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billingrecord_record_type_subscriptionplan'),
        ('chat', '0004_alter_aimodel_options_aimodel_business_type_and_more'),
        ('gateway', '0005_routingrule_match_users_alter_routingrule_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allowed_backend_groups',
            field=models.ManyToManyField(blank=True, help_text='选择后端组后，组内后端提供的所有模型均可用', related_name='allowed_plans', to='gateway.backendgroup', verbose_name='可用后端组'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allowed_backends',
            field=models.ManyToManyField(blank=True, help_text='直接指定后端，该后端提供的所有模型均可用', related_name='allowed_plans', to='gateway.apibackend', verbose_name='可用后端'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='allowed_models',
            field=models.ManyToManyField(blank=True, help_text='指定可用的单个模型；留空则按后端组/后端或全部', related_name='allowed_plans', to='chat.aimodel', verbose_name='可用模型'),
        ),
    ]
