# Generated by Django 6.0.3 on 2026-04-11 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(help_text='用于 URL，英文字母/数字/连字符', max_length=100, unique=True, verbose_name='URL别名')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, help_text='Element Plus 图标名或 emoji', max_length=50, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '知识库分类',
                'verbose_name_plural': '知识库分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='栏目名称')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL别名')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='栏目描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='knowledge.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '知识库栏目',
                'verbose_name_plural': '知识库栏目',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='URL别名')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('cover_image', models.URLField(blank=True, verbose_name='封面图片URL')),
                ('content', models.TextField(verbose_name='正文内容(HTML富文本)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('tags', models.CharField(blank=True, help_text='逗号分隔', max_length=500, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='knowledge.column', verbose_name='所属栏目')),
            ],
            options={
                'verbose_name': '知识库文章',
                'verbose_name_plural': '知识库文章',
                'ordering': ['-is_top', '-sort_order', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='knowledge_a_status_66e656_idx'), models.Index(fields=['column', 'status'], name='knowledge_a_column__141c66_idx')],
            },
        ),
    ]
