# Generated by Django 6.0.3 on 2026-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='用于 URL，字母/数字/连字符；也可使用中文等 Unicode（将编码进路径）', max_length=100, unique=True, verbose_name='URL别名'),
        ),
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, verbose_name='URL别名'),
        ),
    ]
