# Generated by Django 6.0.3 on 2026-03-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200, unique=True, verbose_name='模型ID')),
                ('name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('context_length', models.IntegerField(default=4096, verbose_name='上下文长度')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('pricing_prompt', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='输入价格/token')),
                ('pricing_completion', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='输出价格/token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'ordering': ['-is_free', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='消耗tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新对话', max_length=200, verbose_name='对话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.aimodel', verbose_name='使用模型')),
            ],
            options={
                'verbose_name': '对话',
                'verbose_name_plural': '对话',
                'ordering': ['-updated_at'],
            },
        ),
    ]
