# Generated by Django 6.0.3 on 2026-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='费用(元)'),
        ),
    ]
