# Generated by Django 6.0.3 on 2026-04-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_cost'),
        ('gateway', '0004_requestlog_business_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['business_type', '-is_free', 'name'], 'verbose_name': 'AI模型', 'verbose_name_plural': 'AI模型'},
        ),
        migrations.AddField(
            model_name='aimodel',
            name='business_type',
            field=models.CharField(choices=[('chat', '聊天对话'), ('coding', '编程开发'), ('text2img', '文生图'), ('text2video', '文生视频'), ('translation', '翻译'), ('writing', '写作'), ('analysis', '数据分析'), ('general', '通用')], default='general', max_length=20, verbose_name='业务类型'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='隐藏后前端用户不可选择，但已有对话可继续使用', verbose_name='是否可见'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='source_backend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_models', to='gateway.apibackend', verbose_name='来源后端'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_models', to='gateway.backendgroup', verbose_name='来源后端组'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['business_type', 'is_active'], name='chat_aimode_busines_6c6a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['source_backend'], name='chat_aimode_source__fec83d_idx'),
        ),
    ]
