# Generated by Django 6.0.3 on 2026-03-15 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='账户余额(元)'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_status',
            field=models.CharField(choices=[('active', '正常'), ('suspended', '已暂停'), ('banned', '已封禁')], default='active', max_length=20, verbose_name='账号状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, verbose_name='运营备注'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('free', '免费版'), ('basic', '基础版'), ('pro', '专业版'), ('enterprise', '企业版')], default='free', max_length=20, verbose_name='套餐'),
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Token名称')),
                ('token_key', models.CharField(max_length=64, unique=True, verbose_name='Token值')),
                ('permissions', models.CharField(choices=[('chat', '对话接口'), ('all', '全部接口')], default='chat', max_length=20, verbose_name='权限')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('usage_count', models.BigIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
