# Generated by Django 6.0.3 on 2026-04-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_aimodel_options_aimodel_business_type_and_more'),
        ('users', '0002_user_balance_user_company_user_customer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_models',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='chat.aimodel', verbose_name='可用模型'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sub_account',
            field=models.BooleanField(default=False, verbose_name='是否子账号'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_token_limit',
            field=models.BigIntegerField(default=0, help_text='0 表示使用套餐默认额度', verbose_name='月Token额度'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to=settings.AUTH_USER_MODEL, verbose_name='主账号'),
        ),
    ]
