# Generated by Django 6.0.3 on 2026-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_aimodel_options_aimodel_business_type_and_more'),
        ('gateway', '0005_routingrule_match_users_alter_routingrule_match_type'),
        ('users', '0003_user_allowed_models_user_is_sub_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_backend_groups',
            field=models.ManyToManyField(blank=True, help_text='指定后端组后，该组内所有后端提供的模型均可用', related_name='allowed_users', to='gateway.backendgroup', verbose_name='可用后端组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allowed_models',
            field=models.ManyToManyField(blank=True, help_text='指定可用的单个模型；留空则按后端组或套餐决定', related_name='allowed_users', to='chat.aimodel', verbose_name='可用模型'),
        ),
    ]
